"""
Build src/components/design-system/icon-paths.ts from the Material Symbols
Rounded font that ships with @expo-google-fonts/material-symbols-rounded.

Why: drawing icons as font text depends on how each platform lays out a line
of text, and on iOS that left icons off-centre inside their circles. Drawing
the same glyphs as SVG paths puts every icon exactly in the middle of its
box on every platform. The icon family does not change: these are the
Material Symbols Rounded glyphs, copied out of the font the app already uses.

Run it after adding an icon name to ICONS below:
    pip install fonttools
    python3 scripts/build-icons.py
"""
import glob
import json
import os

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

# Every Material Symbols ligature the app uses, plus the per-screen inventory
# from the design system's iconography foundation. Add a name here, then rerun.
ICONS = sorted({
    'add', 'add_a_photo', 'admin_panel_settings', 'arrow_back', 'arrow_forward', 'arrow_upward',
    'barcode', 'barcode_scanner', 'block', 'bookmark', 'check', 'check_circle', 'checklist',
    'chevron_left', 'chevron_right', 'close', 'cloud_off', 'dangerous', 'delete',
    'do_not_disturb_on', 'edit', 'emergency', 'error', 'expand_less', 'expand_more', 'favorite',
    'filter_alt', 'flag', 'flashlight_off', 'flashlight_on', 'grocery', 'groups', 'history',
    'home', 'info', 'inventory_2', 'keyboard', 'list_alt', 'lock', 'logout', 'mail',
    'manage_accounts', 'monitor_weight', 'more_horiz', 'more_vert', 'no_food', 'notifications',
    'nutrition', 'person', 'person_add', 'photo_camera', 'restaurant', 'rule', 'science',
    'search', 'sell', 'send', 'settings', 'share', 'storefront', 'swap_horiz', 'sync_problem',
    'task_alt', 'tune', 'verified', 'vibration', 'visibility', 'visibility_off', 'warning',
})

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_DIR = os.path.join(ROOT, 'node_modules', '@expo-google-fonts', 'material-symbols-rounded')
OUT = os.path.join(ROOT, 'src', 'components', 'design-system', 'icon-paths.ts')
WEIGHTS = {'regular': '400Regular', 'emphasis': '600SemiBold'}


def ligature_map(font):
    """Map each ligature's text (e.g. 'home') to its glyph name, from the font's GSUB table."""
    cmap = font.getBestCmap()
    char_of = {glyph: chr(code) for code, glyph in cmap.items()}
    found = {}
    for lookup in font['GSUB'].table.LookupList.Lookup:
        for sub in lookup.SubTable:
            sub = getattr(sub, 'ExtSubTable', sub)
            for first, ligatures in getattr(sub, 'ligatures', {}).items():
                for lig in ligatures:
                    text = ''.join(char_of.get(g, '?') for g in [first, *lig.Component])
                    found.setdefault(text, lig.LigGlyph)
    return found


def glyph_paths(font_file):
    font = TTFont(font_file)
    glyphs = font.getGlyphSet()
    ligatures = ligature_map(font)
    paths = {}
    for name in ICONS:
        glyph = ligatures.get(name) or (name if name in glyphs else None)
        if glyph is None:
            raise SystemExit(f'Material Symbols has no icon called "{name}".')
        pen = SVGPathPen(glyphs, ntos=lambda n: str(round(n)))
        # Font outlines point up from the baseline; SVG points down from the
        # top. Flipping inside the 960 unit em box makes the path sit in a
        # "0 0 960 960" viewBox.
        glyphs[glyph].draw(TransformPen(pen, (1, 0, 0, -1, 0, 960)))
        paths[name] = pen.getCommands()
    return paths


def main():
    by_weight = {}
    for key, folder in WEIGHTS.items():
        font_file = glob.glob(os.path.join(FONT_DIR, folder, '*.ttf'))[0]
        by_weight[key] = glyph_paths(font_file)

    lines = [
        '/**',
        ' * GENERATED by scripts/build-icons.py. Do not edit by hand.',
        ' *',
        ' * Material Symbols Rounded outlines, copied from the font the app ships,',
        ' * as SVG paths in a 0 0 960 960 box. `regular` is weight 400 (rest),',
        ' * `emphasis` is weight 600 (selected). Add an icon name to the script and',
        ' * rerun it to add an icon.',
        ' */',
        '',
        'export const iconPaths = {',
    ]
    for name in ICONS:
        regular = json.dumps(by_weight['regular'][name])
        emphasis = json.dumps(by_weight['emphasis'][name])
        lines.append(f'  {name}: {{ regular: {regular}, emphasis: {emphasis} }},')
    lines += ['} as const;', '', 'export type IconName = keyof typeof iconPaths;', '']
    with open(OUT, 'w') as f:
        f.write('\n'.join(lines))
    print(f'Wrote {len(ICONS)} icons to {os.path.relpath(OUT, ROOT)}')


if __name__ == '__main__':
    main()
